language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script:
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

before_script:
  - composer self-update
  - composer update --prefer-source
