language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

script:
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

before_script:
  - composer self-update
  - composer update --prefer-source
