language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

script:
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
  - ./vendor/bin/phpunit

before_script:
  - composer self-update
  - composer update --prefer-source
