#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use ConsoleTools\Symlink\Commands\GenerateSymlinksCommand;

$app = new Application();
$app->add(new GenerateSymlinksCommand());
$app->run();
